#!/bin/sh

# Init submodules
cd "${HOME}"
yadm submodule update --recursive --init

if command -v vim >/dev/null 2>&1; then
  echo "Bootstrapping vim"
  vim '+PlugInstall' '+PlugClean' '+qall'
fi

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstrapping Neovim"

  nvim '+PlugInstall' '+PlugClean' '+qall'
fi

# Install rustup
if ! command -v rustup >/dev/null 2>&1; then
  echo "Downloading rustup"
  curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable
  export PATH="${PATH}:${HOME}/.cargo/bin"
  hash -r
fi
