#!/bin/sh

# Opens a terminal with ssh or a remote desktop view for any of my VMs

declare -A SSH RDP

# {{{ List of VMs running SSH
SSH[debian-9]="debian-9.lan"
SSH[debian-10]="debian-10.lan"
SSH[ci-runner-01]="ci-runner-01.lan"
SSH[ubuntu-16]="ubuntu-16.lan"
SSH[ubuntu-19]="ubuntu-19.lan"
SSH[ubuntu-20]="ubuntu-20.lan"
SSH[freebsd-12]="freebsd-12.lan"
SSH[home-assistant]="hass.lan"
# }}}

# List of VMs running Microsoft RDP
RDP[windows-10]="DESKTOP-JF4DBIP.lan"

all_names="${!SSH[*]} ${!RDP[*]}"

if [ "$#" -eq 1 ]; then
  vm="${1}"
else
  vm=$(echo "${all_names// /$'\n'}" | rofi -dmenu -matching fuzzy -p vm)

  if [ $? -ne 0 ]; then
    exit
  fi
fi

host="${SSH[$vm]}"
if [ "${host}" != "" ]; then
  i3-sensible-terminal -e "/bin/sh -c \"ssh ${host}\"" &
  exit
fi

host="${RDP[$vm]}"
if [ "${host}" != "" ]; then
  case $host in
    DESKTOP-JF4DBIP.lan)
      xfreerdp "/u:User" "/v:${host}" "/p:password" /dynamic-resolution \
        /sound /size:1600x900 /rfx /gfx
      ;;
  esac

  exit
fi

echo "No such host \`${vm}' - available hosts:"

for name in $all_names; do
  echo "* ${name}"
done

exit 1
