#!/bin/sh

# Init submodules
cd "${HOME}"
yadm submodule update --recursive --init

if command -v vim >/dev/null 2>&1; then
  echo "Bootstrapping vim"
  vim '+VundleInstall' '+VundleUpdate' '+VundleClean' '+qall'

fi

